on: push
jobs: 
  testing-action:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -uses: ./.github/actions/hello
      with:
        who-to-reet: "World"
      - run: echo "Time: ${{steps.hello.outputs.time}}"
