on: push
jobs: 
  testing-action:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v2
      -uses: ./.github/actions/issue
       with': 
         token: ${{secrets.GITHUB_TOKEN}}   
         title: title
         body: Body
         assignees: | 
           andrey-krendzel
      - uses: ./.github/actions/hello
        id: hello
      with:
        who-to-greet: "World"
      - run: |
          echo ${{ steps.issue.outputs.issue }}
          echo "Time: ${{ steps.hello.outputs.time ))".
          echo  $HELLO
